base: [grids.yaml, layers.yaml, caches.yaml, sources.yaml]
services:
  demo:
  tms:
    origin: 'nw'

globals:
  # cache options
  cache:
    base_dir: '../cache_data'
    lock_dir: '../cache_data/locks'

    meta_size: [4, 4]
    meta_buffer: 5

  # Point at the correct binary
  mapserver:
    binary: '../mapserv'
    working_dir: '../mapserv'

  # image/transformation options
  image:
    # Quality over speed
    resampling_method: bicubic
    paletted: false
    formats:
      image/png:
        mode: RGBA
        transparent: true
