sources:
  niger_mar_2010_321_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_mar_2010_321
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'
  niger_mar_2010_432_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_mar_2010_432
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'
  niger_mar_2010_742_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_mar_2010_742
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'

  niger_oct_2012_321_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_oct_2012_321
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'
  niger_oct_2012_432_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_oct_2012_432
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'
  niger_oct_2012_742_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: niger_oct_2012_742
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/niger_mar_2010.wkt'
      polygons_srs: 'EPSG:4326'

  bc_landsat_oct_2012_321_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: bc_landsat_oct_2012_321
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/bc_landsat_oct_2012.wkt'
      polygons_srs: 'EPSG:4326'
  bc_landsat_oct_2012_432_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: bc_landsat_oct_2012_432
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/bc_landsat_oct_2012.wkt'
      polygons_srs: 'EPSG:4326'
  bc_landsat_oct_2012_742_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: bc_landsat_oct_2012_742
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/bc_landsat_oct_2012.wkt'
      polygons_srs: 'EPSG:4326'

  madagascar_mar_4_2013_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: madagascar_mar_4_2013
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/madagascar_mar_4_2013.wkt'
      polygons_srs: 'EPSG:4326'

  orb32536_source:
    type: mapserver
    supported_srs: ['EPSG:3857']
    req:
      layers: orb32536
      map: './mapfile.map'
    coverage:
      polygons: 'wkt/orb32536.wkt'
      polygons_srs: 'EPSG:4326'
